from: markdown

to  : pdf

output-file: scribe.pdf

input-files:
- 01-primer.md
- 06-hmm.md
- 15-genomicIntervals.md

table-of-contents: true

number-sections: true

pdf-engine: xelatex

indented-code-classes: 
- python

highlight-style: tango

filters:
- pandoc-crossref

top-level-division: chapter

html-math-method:
  method: mathjax

cite-method: biblatex

metadata:
  documentclass: report
  papersize: letter
  geometry: "left=1in,right=1in,top=1in,bottom=1in"
  figPrefix: "Figure"
